export const Strings = {
  imagePlaceholder: "No image selected",
  pictureBtn: "Choose a picture",
  pictureTitle: "Picture",
  lifestyleTitle: "LifeStyle",
  personalInfo: "Presonal Information",
  stylistInfo: "Stylist Information",
  measurementTitle: "Measurements",
  othersTitle: "Others",
  aboutTitle: "About",
  next: "Next",
  back: "Back",

  stylist: "STYLIST",
  customer: "CUSTOMER",
  signin: "SIGN IN",
  signup: "SIGN UP",
  newAccountQuestion: "DON'T HAVE AN ACCOUNT?",
  alreadyHaveAnAccount: "ALREADY HAVE AN ACCOUNT?",

  usernamePlaceholder: "USERNAME",
  passwordPlaceholder: "PASSWORD",
  confirmPasswordPlaceholder: "CONFIRM PASSWORD",
  alertTitleError: "Error",
  alertUsernameEmpty: "Please enter your username.",
  alertPasswordEmpty: "Please enter your password.",
  alertUsernameTooLong: "Username cannot exceed 14 characters.",
  alertPasswordTooLong: "Password cannot exceed 14 characters.",
  alertPasswordMismatch: "Passwords do not match.",
  alertEnterUsername: "Please enter your username.",
  alertEnterPassword: "Please enter your password.",
};
